// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rating.proto

package rating

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRatingRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingRequest) Reset()         { *m = GetRatingRequest{} }
func (m *GetRatingRequest) String() string { return proto.CompactTextString(m) }
func (*GetRatingRequest) ProtoMessage()    {}
func (*GetRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{0}
}

func (m *GetRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingRequest.Unmarshal(m, b)
}
func (m *GetRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingRequest.Marshal(b, m, deterministic)
}
func (m *GetRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingRequest.Merge(m, src)
}
func (m *GetRatingRequest) XXX_Size() int {
	return xxx_messageInfo_GetRatingRequest.Size(m)
}
func (m *GetRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingRequest proto.InternalMessageInfo

func (m *GetRatingRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRatingResponse struct {
	Rating               float32  `protobuf:"fixed32,1,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingResponse) Reset()         { *m = GetRatingResponse{} }
func (m *GetRatingResponse) String() string { return proto.CompactTextString(m) }
func (*GetRatingResponse) ProtoMessage()    {}
func (*GetRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{1}
}

func (m *GetRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingResponse.Unmarshal(m, b)
}
func (m *GetRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingResponse.Marshal(b, m, deterministic)
}
func (m *GetRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingResponse.Merge(m, src)
}
func (m *GetRatingResponse) XXX_Size() int {
	return xxx_messageInfo_GetRatingResponse.Size(m)
}
func (m *GetRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingResponse proto.InternalMessageInfo

func (m *GetRatingResponse) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type AddRatingRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Rating               int32    `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRatingRequest) Reset()         { *m = AddRatingRequest{} }
func (m *AddRatingRequest) String() string { return proto.CompactTextString(m) }
func (*AddRatingRequest) ProtoMessage()    {}
func (*AddRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{2}
}

func (m *AddRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRatingRequest.Unmarshal(m, b)
}
func (m *AddRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRatingRequest.Marshal(b, m, deterministic)
}
func (m *AddRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRatingRequest.Merge(m, src)
}
func (m *AddRatingRequest) XXX_Size() int {
	return xxx_messageInfo_AddRatingRequest.Size(m)
}
func (m *AddRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRatingRequest proto.InternalMessageInfo

func (m *AddRatingRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddRatingRequest) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *AddRatingRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type AddRatingResponse struct {
	Ok                   string   `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRatingResponse) Reset()         { *m = AddRatingResponse{} }
func (m *AddRatingResponse) String() string { return proto.CompactTextString(m) }
func (*AddRatingResponse) ProtoMessage()    {}
func (*AddRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{3}
}

func (m *AddRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRatingResponse.Unmarshal(m, b)
}
func (m *AddRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRatingResponse.Marshal(b, m, deterministic)
}
func (m *AddRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRatingResponse.Merge(m, src)
}
func (m *AddRatingResponse) XXX_Size() int {
	return xxx_messageInfo_AddRatingResponse.Size(m)
}
func (m *AddRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRatingResponse proto.InternalMessageInfo

func (m *AddRatingResponse) GetOk() string {
	if m != nil {
		return m.Ok
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRatingRequest)(nil), "GetRatingRequest")
	proto.RegisterType((*GetRatingResponse)(nil), "GetRatingResponse")
	proto.RegisterType((*AddRatingRequest)(nil), "AddRatingRequest")
	proto.RegisterType((*AddRatingResponse)(nil), "AddRatingResponse")
}

func init() { proto.RegisterFile("rating.proto", fileDescriptor_f98441b067dcd23a) }

var fileDescriptor_f98441b067dcd23a = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2c, 0xc9,
	0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0x12, 0x70, 0x4f, 0x2d, 0x09,
	0x02, 0x0b, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x71, 0x31, 0x79, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x31, 0x79, 0xa6, 0x28, 0x69, 0x73, 0x09, 0x22, 0xa9, 0x29,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe3, 0x62, 0x83, 0x88, 0x80, 0x15, 0x32, 0x05, 0x41,
	0x79, 0x4a, 0x7e, 0x5c, 0x02, 0x8e, 0x29, 0x29, 0x78, 0x0d, 0x04, 0xe9, 0x85, 0x38, 0x42, 0x82,
	0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0xca, 0x13, 0x12, 0xe2, 0x62, 0x29, 0x2d, 0x4e, 0x2d, 0x92,
	0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x94, 0xb9, 0x04, 0x91, 0xcc, 0x83, 0x5a,
	0xce, 0xc7, 0xc5, 0x94, 0x9f, 0x0d, 0x36, 0x90, 0x33, 0x88, 0x29, 0x3f, 0xdb, 0xa8, 0x00, 0xe6,
	0x18, 0x21, 0x23, 0x2e, 0x4e, 0xb8, 0x5b, 0x85, 0x04, 0xf5, 0xd0, 0xfd, 0x26, 0x25, 0xa4, 0x87,
	0xe9, 0x15, 0x23, 0x2e, 0x4e, 0xb8, 0x15, 0x42, 0x82, 0x7a, 0xe8, 0xce, 0x97, 0x12, 0xd2, 0xc3,
	0x70, 0x41, 0x12, 0x1b, 0x38, 0xf8, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x93, 0x65, 0x10,
	0xd2, 0x4e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RatingClient is the client API for Rating service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RatingClient interface {
	GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*GetRatingResponse, error)
	AddRating(ctx context.Context, in *AddRatingRequest, opts ...grpc.CallOption) (*AddRatingResponse, error)
}

type ratingClient struct {
	cc *grpc.ClientConn
}

func NewRatingClient(cc *grpc.ClientConn) RatingClient {
	return &ratingClient{cc}
}

func (c *ratingClient) GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*GetRatingResponse, error) {
	out := new(GetRatingResponse)
	err := c.cc.Invoke(ctx, "/Rating/GetRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) AddRating(ctx context.Context, in *AddRatingRequest, opts ...grpc.CallOption) (*AddRatingResponse, error) {
	out := new(AddRatingResponse)
	err := c.cc.Invoke(ctx, "/Rating/AddRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServer is the server API for Rating service.
type RatingServer interface {
	GetRating(context.Context, *GetRatingRequest) (*GetRatingResponse, error)
	AddRating(context.Context, *AddRatingRequest) (*AddRatingResponse, error)
}

// UnimplementedRatingServer can be embedded to have forward compatible implementations.
type UnimplementedRatingServer struct {
}

func (*UnimplementedRatingServer) GetRating(ctx context.Context, req *GetRatingRequest) (*GetRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRating not implemented")
}
func (*UnimplementedRatingServer) AddRating(ctx context.Context, req *AddRatingRequest) (*AddRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRating not implemented")
}

func RegisterRatingServer(s *grpc.Server, srv RatingServer) {
	s.RegisterService(&_Rating_serviceDesc, srv)
}

func _Rating_GetRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rating/GetRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetRating(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_AddRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).AddRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rating/AddRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).AddRating(ctx, req.(*AddRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rating_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Rating",
	HandlerType: (*RatingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRating",
			Handler:    _Rating_GetRating_Handler,
		},
		{
			MethodName: "AddRating",
			Handler:    _Rating_AddRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rating.proto",
}
